### ISSUE TITLE
Added Hello World In Cpp

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Hello-World-#10]

**Comment by 96RadhikaJadhav** [comment]
@Ayush7614  Can I work on it?

**Comment by Ayush7614** [comment]
@96RadhikaJadhav go ahead

**Comment by Ayush7614** [comment]
@96RadhikaJadhav go ahead

**Comment by 96RadhikaJadhav** [comment]
@Ayush7614 I could see, there is already a folder for cpp and program is also there. So you can close this issue.
