### ISSUE TITLE
Added Hello World In HTML5

### ISSUE THREAD

**Issue by Ayush7614** [Ayush7614/Hello-World-#3]

**Comment by 96RadhikaJadhav** [comment]
@Ayush7614  Can I work on this issue and all other #4 #2 #1 also?

**Comment by Ayush7614** [comment]
Sure You work on the first #1 but not trying copy paste

**Comment by Ayush7614** [comment]
Just try it then contribute it

**Comment by Ayush7614** [comment]
It looks good to me Thanks for Contribution
